### ISSUE TITLE
How can I preview sql idcard ingame?

### ISSUE THREAD

**Issue by szileni** [Fixitfy/FX-Idcard#2]
Hello!

Any way to preview my created idcard with "Config.TakeCardType = "sql""?
With this method no item was created in my inventory, only my photo. (VORP)
There is keypress or command for this?

Thanks,
Szileni

**Comment by Fixitfy** [comment]
## Greetings,
### I hope you are well.

**You can access the preview by triggering the following event. You can do this either via the radialmenu using fx-radialmenu or via command. This is completely up to you.**
```lua
TriggerEvent('fx-idcard:client:showIDCardSQL')
```

### You can join our discord server to get faster answers. https://discord.fixitfy.com.tr

### King Rewards!

**Comment by szileni** [comment]
Thank you, works fine!
